require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.4.0
  # 除外するファイル
  Exclude:
    - bin/*
    - db/**/*
    - config/**/*

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics:
  Exclude:
    - app/controllers/states_controller.rb

Style/GuardClause:
  Exclude:
    - app/controllers/application_controller.rb
    - app/controllers/states_controller.rb

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# TODO: current_userのインスタンス化を取りやめても影響ないか確認
Rails/HelperInstanceVariable:
  Enabled: false

