require:
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.4.0
  # 除外するファイル
  Exclude:
    - vendor/**/*
    - bin/*
    - db/**/*
    - config/**/*
    - Gemfile

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Next:
  Enabled: false

Naming/PredicateName:
  Enabled: false

# after delete
Rails/HelperInstanceVariable:
  Enabled: false

